import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";

const robotoSans = Roboto({
  variable: "--roboto-sans",
  subsets: ["latin", "cyrillic"],
});

const robotoMonoSans = Roboto_Mono({
  variable: "--roboto-mono",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoSans.variable} ${robotoMonoSans.variable} antialiased`}
        cz-shortcut-listen="true"
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
